Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,26 +1,56 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/configuration-reference
 version: 2.1
+orbs:
+  node: circleci/node@5.1.0
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/configuration-reference/#jobs
 jobs:
-  say-hello:
-    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/configuration-reference/#executor-job
-    docker:
-      - image: cimg/base:stable
-    # Add steps to the job
-    # See: https://circleci.com/docs/configuration-reference/#steps
+  build_and_test:
+    executor:
+      name: node/default
+      tag: "18.16"
     steps:
       - checkout
+      - run: node --version
+      - node/install-packages:
+          pkg-manager: npm
       - run:
-          name: "Say hello"
-          command: "echo Hello, World!"
+          command: npm run test
+          name: Run unit tests
+      # - run:
+      #     command: npm run build
+      #     name: Build server
+      # - run:
+      #     command: npm run start
+      #     name: Start server
+      #     background: true
+      # - run:
+      #     command: sleep 30 && curl -I localhost:3000
+      #     name: Verify server is running
+  deploy:
+    machine:
+      image: ubuntu-2004:current
+    resource_class: medium
+    steps:
+      - run:
+          name: Deploy API to Render
+          command: |
+            response=$(curl -s -w "%{http_code}" -o response.txt $DEPLOY_URI)
+            response_code=${response:(-3)}
+            if [ $response_code -eq 200 ]; then
+              echo "Deployment successful!"
+              cat response.txt  # Print the response body
+            else
+              echo "Deployment failed with response code: $response_code"
+              cat response.txt  # Print the response body
+              exit 1
+            fi
 
-# Orchestrate jobs using workflows
-# See: https://circleci.com/docs/configuration-reference/#workflows
 workflows:
-  say-hello-workflow:
+  build_and_test_app:
     jobs:
-      - say-hello
+      - build_and_test
+      - deploy:
+          requires:
+            - build_and_test
+          filters:
+            branches:
+              only: main
